In [32]:
import pandas as pd
pd.set_option('display.float_format', '{:.1e}'.format)

In [33]:
# read the stored data

data = pd.read_csv("data-2.csv")
data

,muTilde,mqt3,mut3,cG,cW,cH,cHD,cHBox,cHB,cHW,...,cHq1_33,cHq3_33,cuG_33,cuW_33,cuB_33,cuu_3333,cqq1_3333,cqq3_3333,cqu1_3333,cqu8_3333
0,9.0e-01,1.1e+00,6.4e+00,3.8e-05,-1.0e-07,-1.2e-03,-2.0e-03,3.9e-05,5.3e-06,9.6e-05,...,8.2e-04,-8.5e-04,-1.1e-03,1.4e-05,1.2e-04,-8.3e-03,-1.7e-04,-1.4e-04,1.8e-03,2.2e-03
1,1.3e+00,6.2e+00,2.1e+00,6.3e-06,-4.9e-06,-2.5e-04,-6.8e-05,-2.1e-04,1.5e-05,2.9e-06,...,-1.2e-05,7.8e-05,-2.2e-04,5.8e-05,-5.8e-05,-5.6e-04,-7.7e-04,-5.7e-04,1.2e-03,3.9e-04
2,1.3e+00,8.4e+00,7.8e+00,1.1e-06,-5.5e-06,-5.2e-05,-4.2e-05,-4.9e-05,1.3e-06,1.7e-06,...,1.1e-05,-8.6e-06,-4.8e-05,9.0e-06,-1.9e-06,-3.2e-04,-1.1e-04,-7.1e-05,3.8e-04,7.3e-05
3,1.4e+00,6.1e+00,4.9e+00,2.2e-06,-4.7e-06,-8.8e-05,-7.1e-05,-6.6e-05,3.1e-06,3.1e-06,...,1.9e-05,-9.1e-07,-9.7e-05,1.9e-05,-8.0e-06,-5.6e-04,-2.3e-04,-1.6e-04,7.4e-04,1.5e-04
4,7.5e-01,8.6e+00,1.7e+00,8.3e-06,-1.6e-05,-5.9e-04,-5.2e-05,-4.5e-04,2.6e-05,1.7e-06,...,-7.2e-05,2.4e-04,-3.2e-04,1.2e-04,-1.3e-04,-3.3e-04,-1.5e-03,-1.1e-03,9.6e-04,5.5e-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,6.9e-01,5.8e+00,2.5e+00,5.3e-06,-1.9e-05,-3.2e-04,-9.6e-05,-2.8e-04,1.3e-05,3.6e-06,...,-3.0e-05,1.2e-04,-2.3e-04,7.4e-05,-6.4e-05,-6.8e-04,-9.1e-04,-6.2e-04,1.4e-03,3.6e-04
96,1.2e+00,5.1e+00,8.7e+00,2.1e-06,-6.0e-06,-8.4e-05,-1.0e-04,-4.6e-05,1.2e-06,4.6e-06,...,5.0e-05,-5.5e-05,-9.2e-05,7.4e-06,9.5e-06,-7.8e-04,-8.7e-05,-5.9e-05,5.2e-04,1.4e-04
97,1.1e+00,5.5e+00,3.4e+00,3.5e-06,-7.7e-06,-1.6e-04,-9.1e-05,-1.3e-04,6.3e-06,3.9e-06,...,1.2e-05,2.9e-05,-1.5e-04,3.6e-05,-2.4e-05,-7.1e-04,-4.5e-04,-3.1e-04,1.1e-03,2.4e-04
98,7.2e-01,9.2e+00,3.9e+00,2.1e-06,-1.7e-05,-1.4e-04,-4.8e-05,-1.7e-04,5.2e-06,1.5e-06,...,-2.4e-05,4.8e-05,-9.5e-05,3.4e-05,-2.8e-05,-2.8e-04,-4.0e-04,-2.7e-04,6.0e-04,1.5e-04
99,1.2e+00,7.9e+00,2.0e+00,6.9e-06,-6.6e-06,-4.0e-04,-4.8e-05,-2.9e-04,2.0e-05,1.9e-06,...,-2.7e-05,1.3e-04,-2.4e-04,7.3e-05,-7.9e-05,-3.7e-04,-9.6e-04,-7.1e-04,9.5e-04,4.3e-04

In [34]:
data_abs = data.abs()
data_abs.sort_values(by=['cqu8_3333'],ascending=False)[['muTilde', 'mqt3', 'mut3', 'cH', 'cHD', 'cHq1_33', 'cuG_33', 'cuu_3333', 'cqu1_3333','cqu8_3333']]

,muTilde,mqt3,mut3,cH,cHD,cHq1_33,cuG_33,cuu_3333,cqu1_3333,cqu8_3333
27,5.5e-01,8.2e-01,9.2e+00,2.8e-03,4.1e-03,1.8e-03,2.2e-03,1.8e-02,1.5e-03,4.2e-03
0,9.0e-01,1.1e+00,6.4e+00,1.2e-03,2.0e-03,8.2e-04,1.1e-03,8.3e-03,1.8e-03,2.2e-03
87,8.9e-01,1.2e+00,8.4e+00,1.1e-03,1.7e-03,7.4e-04,9.5e-04,7.6e-03,1.2e-03,1.8e-03
6,9.2e-01,2.7e+00,1.0e+00,2.4e-04,2.8e-04,8.6e-05,8.6e-04,2.5e-03,4.8e-03,1.6e-03
43,9.8e-01,1.3e+00,8.3e+00,9.7e-04,1.5e-03,6.3e-04,8.2e-04,6.5e-03,1.2e-03,1.6e-03
...,...,...,...,...,...,...,...,...,...,...
86,7.7e-01,9.1e+00,7.6e+00,5.9e-05,4.7e-05,2.3e-06,4.5e-05,2.9e-04,3.7e-04,6.8e-05
20,1.4e+00,9.1e+00,7.5e+00,4.9e-05,3.6e-05,7.3e-06,4.4e-05,2.7e-04,3.5e-04,6.8e-05
40,6.3e-01,8.6e+00,9.0e+00,5.7e-05,5.8e-05,6.6e-06,4.4e-05,3.3e-04,3.5e-04,6.5e-05
76,7.8e-01,8.8e+00,9.0e+00,5.2e-05,4.8e-05,7.5e-06,4.2e-05,3.0e-04,3.3e-04,6.3e-05
21,5.1e-01,9.5e+00,8.2e+00,6.2e-05,6.1e-05,3.5e-06,4.1e-05,2.7e-04,3.4e-04,6.1e-05

In [38]:
data.iloc[[27,49,0,87,43,79,6,61,35,53,16],[0, 1, 2, 5, 6, 14, 16,19,22,23]]

,muTilde,mqt3,mut3,cH,cHD,cHq1_33,cuG_33,cuu_3333,cqu1_3333,cqu8_3333
27,5.5e-01,8.2e-01,9.2e+00,-2.8e-03,-4.1e-03,1.8e-03,-2.2e-03,-1.8e-02,1.5e-03,4.2e-03
49,8.4e-01,6.4e+00,1.1e+00,-1.3e-03,-7.6e-05,-6.7e-05,-6.2e-04,-5.8e-04,1.7e-03,1.2e-03
0,9.0e-01,1.1e+00,6.4e+00,-1.2e-03,-2.0e-03,8.2e-04,-1.1e-03,-8.3e-03,1.8e-03,2.2e-03
87,8.9e-01,1.2e+00,8.4e+00,-1.1e-03,-1.7e-03,7.4e-04,-9.5e-04,-7.6e-03,1.2e-03,1.8e-03
43,9.8e-01,1.3e+00,8.3e+00,-9.7e-04,-1.5e-03,6.3e-04,-8.2e-04,-6.5e-03,1.2e-03,1.6e-03
79,5.1e-01,1.5e+00,6.2e+00,-8.1e-04,-1.2e-03,6.2e-04,-8.4e-04,-7.7e-03,2.0e-03,1.4e-03
6,9.2e-01,2.7e+00,1.0e+00,-2.4e-04,-2.8e-04,-8.6e-05,-8.6e-04,-2.5e-03,4.8e-03,1.6e-03
61,1.3e+00,2.5e+00,1.9e+00,1.9e-04,-2.5e-04,-1.7e-05,-4.8e-04,-2.4e-03,3.2e-03,8.2e-04
35,1.2e+00,1.4e+00,2.8e+00,1.3e-04,-7.1e-04,2.9e-04,-7.8e-04,-5.2e-03,3.5e-03,1.5e-03
53,5.6e-01,2.6e+00,2.9e+00,-3.9e-04,-4.1e-04,1.6e-04,-4.3e-04,-3.1e-03,3.1e-03,6.7e-04
16,6.0e-01,3.3e+00,2.4e+00,-4.0e-04,-2.6e-04,4.5e-05,-3.7e-04,-2.0e-03,2.9e-03,5.8e-04